/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TrackingNumberRequest {
    requestId: bigint;
    createdAt: bigint;
    receiverName: string;
    senderName: string;
    parcelDescription: string;
}
export interface PackageTracking {
    trackingNumber: string;
    createdAt: bigint;
    statusHistory: Array<[TrackingStatus, bigint]>;
    receiverName: string;
    senderName: string;
    currentStatus: TrackingStatus;
}
export interface DeliveryRequest {
    deliveryAddress: string;
    senderPhone: string;
    trackingNumber: string;
    requestId: bigint;
    parcelWeight: string;
    createdAt: bigint;
    pickupAddress: string;
    receiverName: string;
    senderName: string;
    receiverPhone: string;
    parcelDescription: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface Testimonial {
    content: string;
    createdAt: bigint;
    authorName: string;
    authorImage: string;
    rating: number;
}
export enum TrackingStatus {
    arrivedAtFacility = "arrivedAtFacility",
    outForDelivery = "outForDelivery",
    inTransit = "inTransit",
    delivered = "delivered",
    accepted = "accepted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cleanupOldDeliveredPackages(): Promise<void>;
    createTrackingNumberRequest(senderName: string, receiverName: string, parcelDescription: string): Promise<void>;
    generateTrackingNumberForDelivery(requestId: bigint): Promise<string>;
    getAllDeliveryRequests(): Promise<Array<DeliveryRequest>>;
    getAllTestimonials(): Promise<Array<Testimonial>>;
    getAllTrackingNumberRequests(): Promise<Array<TrackingNumberRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPublicTestimonials(): Promise<Array<Testimonial>>;
    getTrackingInfo(trackingNumber: string): Promise<PackageTracking>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitDeliveryRequest(senderName: string, senderPhone: string, pickupAddress: string, receiverName: string, receiverPhone: string, deliveryAddress: string, parcelDescription: string, parcelWeight: string): Promise<string>;
    submitTestimonial(authorName: string, content: string, rating: number, authorImage: string): Promise<void>;
    updateTrackingStatus(trackingNumber: string, newStatus: TrackingStatus): Promise<void>;
}
import type { PackageTracking as _PackageTracking, TrackingStatus as _TrackingStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async cleanupOldDeliveredPackages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanupOldDeliveredPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanupOldDeliveredPackages();
            return result;
        }
    }
    async createTrackingNumberRequest(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrackingNumberRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrackingNumberRequest(arg0, arg1, arg2);
            return result;
        }
    }
    async generateTrackingNumberForDelivery(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateTrackingNumberForDelivery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateTrackingNumberForDelivery(arg0);
            return result;
        }
    }
    async getAllDeliveryRequests(): Promise<Array<DeliveryRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeliveryRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeliveryRequests();
            return result;
        }
    }
    async getAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials();
            return result;
        }
    }
    async getAllTrackingNumberRequests(): Promise<Array<TrackingNumberRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrackingNumberRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrackingNumberRequests();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPublicTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicTestimonials();
            return result;
        }
    }
    async getTrackingInfo(arg0: string): Promise<PackageTracking> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrackingInfo(arg0);
                return from_candid_PackageTracking_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrackingInfo(arg0);
            return from_candid_PackageTracking_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitDeliveryRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDeliveryRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDeliveryRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async submitTestimonial(arg0: string, arg1: string, arg2: number, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestimonial(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestimonial(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTrackingStatus(arg0: string, arg1: TrackingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrackingStatus(arg0, to_candid_TrackingStatus_n12(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrackingStatus(arg0, to_candid_TrackingStatus_n12(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_PackageTracking_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PackageTracking): PackageTracking {
    return from_candid_record_n7(uploadFile, downloadFile, value);
}
function from_candid_TrackingStatus_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrackingStatus): TrackingStatus {
    return from_candid_variant_n11(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trackingNumber: string;
    createdAt: bigint;
    statusHistory: Array<[_TrackingStatus, bigint]>;
    receiverName: string;
    senderName: string;
    currentStatus: _TrackingStatus;
}): {
    trackingNumber: string;
    createdAt: bigint;
    statusHistory: Array<[TrackingStatus, bigint]>;
    receiverName: string;
    senderName: string;
    currentStatus: TrackingStatus;
} {
    return {
        trackingNumber: value.trackingNumber,
        createdAt: value.createdAt,
        statusHistory: from_candid_vec_n8(uploadFile, downloadFile, value.statusHistory),
        receiverName: value.receiverName,
        senderName: value.senderName,
        currentStatus: from_candid_TrackingStatus_n10(uploadFile, downloadFile, value.currentStatus)
    };
}
function from_candid_tuple_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_TrackingStatus, bigint]): [TrackingStatus, bigint] {
    return [
        from_candid_TrackingStatus_n10(uploadFile, downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arrivedAtFacility: null;
} | {
    outForDelivery: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} | {
    accepted: null;
}): TrackingStatus {
    return "arrivedAtFacility" in value ? TrackingStatus.arrivedAtFacility : "outForDelivery" in value ? TrackingStatus.outForDelivery : "inTransit" in value ? TrackingStatus.inTransit : "delivered" in value ? TrackingStatus.delivered : "accepted" in value ? TrackingStatus.accepted : value;
}
function from_candid_variant_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_TrackingStatus, bigint]>): Array<[TrackingStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n9(uploadFile, downloadFile, x));
}
function to_candid_TrackingStatus_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrackingStatus): _TrackingStatus {
    return to_candid_variant_n13(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_variant_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrackingStatus): {
    arrivedAtFacility: null;
} | {
    outForDelivery: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} | {
    accepted: null;
} {
    return value == TrackingStatus.arrivedAtFacility ? {
        arrivedAtFacility: null
    } : value == TrackingStatus.outForDelivery ? {
        outForDelivery: null
    } : value == TrackingStatus.inTransit ? {
        inTransit: null
    } : value == TrackingStatus.delivered ? {
        delivered: null
    } : value == TrackingStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
