/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DeliveryRequest {
  'deliveryAddress' : string,
  'senderPhone' : string,
  'trackingNumber' : string,
  'requestId' : bigint,
  'parcelWeight' : string,
  'createdAt' : bigint,
  'pickupAddress' : string,
  'receiverName' : string,
  'senderName' : string,
  'receiverPhone' : string,
  'parcelDescription' : string,
}
export interface PackageTracking {
  'trackingNumber' : string,
  'createdAt' : bigint,
  'statusHistory' : Array<[TrackingStatus, bigint]>,
  'receiverName' : string,
  'senderName' : string,
  'currentStatus' : TrackingStatus,
}
export interface Testimonial {
  'content' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'authorImage' : string,
  'rating' : number,
}
export interface TrackingNumberRequest {
  'requestId' : bigint,
  'createdAt' : bigint,
  'receiverName' : string,
  'senderName' : string,
  'parcelDescription' : string,
}
export type TrackingStatus = { 'arrivedAtFacility' : null } |
  { 'outForDelivery' : null } |
  { 'inTransit' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanupOldDeliveredPackages' : ActorMethod<[], undefined>,
  'createTrackingNumberRequest' : ActorMethod<
    [string, string, string],
    undefined
  >,
  'generateTrackingNumberForDelivery' : ActorMethod<[bigint], string>,
  'getAllDeliveryRequests' : ActorMethod<[], Array<DeliveryRequest>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getAllTrackingNumberRequests' : ActorMethod<
    [],
    Array<TrackingNumberRequest>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPublicTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getTrackingInfo' : ActorMethod<[string], PackageTracking>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDeliveryRequest' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    string
  >,
  'submitTestimonial' : ActorMethod<
    [string, string, number, string],
    undefined
  >,
  'updateTrackingStatus' : ActorMethod<[string, TrackingStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];