/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DeliveryRequest = IDL.Record({
  'deliveryAddress' : IDL.Text,
  'senderPhone' : IDL.Text,
  'trackingNumber' : IDL.Text,
  'requestId' : IDL.Nat,
  'parcelWeight' : IDL.Text,
  'createdAt' : IDL.Int,
  'pickupAddress' : IDL.Text,
  'receiverName' : IDL.Text,
  'senderName' : IDL.Text,
  'receiverPhone' : IDL.Text,
  'parcelDescription' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'authorImage' : IDL.Text,
  'rating' : IDL.Nat8,
});
export const TrackingNumberRequest = IDL.Record({
  'requestId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'receiverName' : IDL.Text,
  'senderName' : IDL.Text,
  'parcelDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const TrackingStatus = IDL.Variant({
  'arrivedAtFacility' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'inTransit' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const PackageTracking = IDL.Record({
  'trackingNumber' : IDL.Text,
  'createdAt' : IDL.Int,
  'statusHistory' : IDL.Vec(IDL.Tuple(TrackingStatus, IDL.Int)),
  'receiverName' : IDL.Text,
  'senderName' : IDL.Text,
  'currentStatus' : TrackingStatus,
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cleanupOldDeliveredPackages' : IDL.Func([], [], []),
  'createTrackingNumberRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'generateTrackingNumberForDelivery' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'getAllDeliveryRequests' : IDL.Func(
      [],
      [IDL.Vec(DeliveryRequest)],
      ['query'],
    ),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getAllTrackingNumberRequests' : IDL.Func(
      [],
      [IDL.Vec(TrackingNumberRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPublicTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getTrackingInfo' : IDL.Func([IDL.Text], [PackageTracking], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDeliveryRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'submitTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat8, IDL.Text],
      [],
      [],
    ),
  'updateTrackingStatus' : IDL.Func([IDL.Text, TrackingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DeliveryRequest = IDL.Record({
    'deliveryAddress' : IDL.Text,
    'senderPhone' : IDL.Text,
    'trackingNumber' : IDL.Text,
    'requestId' : IDL.Nat,
    'parcelWeight' : IDL.Text,
    'createdAt' : IDL.Int,
    'pickupAddress' : IDL.Text,
    'receiverName' : IDL.Text,
    'senderName' : IDL.Text,
    'receiverPhone' : IDL.Text,
    'parcelDescription' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'authorImage' : IDL.Text,
    'rating' : IDL.Nat8,
  });
  const TrackingNumberRequest = IDL.Record({
    'requestId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'receiverName' : IDL.Text,
    'senderName' : IDL.Text,
    'parcelDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const TrackingStatus = IDL.Variant({
    'arrivedAtFacility' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'inTransit' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const PackageTracking = IDL.Record({
    'trackingNumber' : IDL.Text,
    'createdAt' : IDL.Int,
    'statusHistory' : IDL.Vec(IDL.Tuple(TrackingStatus, IDL.Int)),
    'receiverName' : IDL.Text,
    'senderName' : IDL.Text,
    'currentStatus' : TrackingStatus,
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cleanupOldDeliveredPackages' : IDL.Func([], [], []),
    'createTrackingNumberRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'generateTrackingNumberForDelivery' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'getAllDeliveryRequests' : IDL.Func(
        [],
        [IDL.Vec(DeliveryRequest)],
        ['query'],
      ),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getAllTrackingNumberRequests' : IDL.Func(
        [],
        [IDL.Vec(TrackingNumberRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPublicTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getTrackingInfo' : IDL.Func([IDL.Text], [PackageTracking], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDeliveryRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'submitTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat8, IDL.Text],
        [],
        [],
      ),
    'updateTrackingStatus' : IDL.Func([IDL.Text, TrackingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };